name: Build and deploy Node.js app to Azure Web App - skyline-backend-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (inside backend folder)
        run: |
          cd backend
          npm install

      - name: Zip artifact for deployment (backend)
        run: |
          cd backend
          zip -r ../release.zip ./*  # Do not include .env here if using Azure environment variables

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d backend  # Unzip into the backend directory

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: '59a2c969-df6e-4928-a354-32d1ebeb014d'  # Your Client ID
          tenant-id: '14f9ce5a-7329-4e53-8d21-ed5e8295f94a'  # Your Tenant ID
          subscription-id: '91db478e-0d60-45da-bad1-9b3da73d66be'  # Your Subscription ID
          client-secret: 'BYp8Q~5jMG1e54v0yX3UZ_762pFhcyNilsU5JcK~'  # Your Client Secret

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'skyline-backend-api'  # Your app name
          slot-name: 'Production'
          package: backend  # Deploy from the backend folder
